export const MENU = {
  cakes: [
    {
      id: "cake1",
      img: "../img/botões/Cakes.png",
      name: "Bolo de Chocolate",
      dsc: "Sabor intenso de chocolate",
      price: 10.0,
    },
    {
      id: "cake2",
      img: "../img/botões/Cakes.png",
      name: "Bolo de Baunilha",
      dsc: "Sabor clássico de baunilha",
      price: 10.0,
    },
    {
      id: "cake3",
      img: "../img/botões/Cakes.png",
      name: "Bolo Red Velvet",
      dsc: "Suave e cremoso",
      price: 10.0,
    },
    {
      id: "cake4",
      img: "../img/botões/Cakes.png",
      name: "Bolo de Limão",
      dsc: "Toque cítrico de limão",
      price: 10.0,
    },
    {
      id: "cake5",
      img: "../img/botões/Cakes.png",
      name: "Bolo de Morango",
      dsc: "Sabor doce de morango",
      price: 10.0,
    },
    {
      id: "cake6",
      img: "../img/botões/Cakes.png",
      name: "Bolo de Laranja",
      dsc: "Toque cítrico refrescante",
      price: 10.0,
    },
    {
      id: "cake7",
      img: "../img/botões/Cakes.png",
      name: "Bolo de Cenoura",
      dsc: "Clássico com cobertura de chocolate",
      price: 10.0,
    },
    {
      id: "cake8",
      img: "../img/botões/Cakes.png",
      name: "Bolo de Coco",
      dsc: "Textura macia com coco ralado",
      price: 10.0,
    },
    {
      id: "cake9",
      img: "../img/botões/Cakes.png",
      name: "Bolo de Amêndoas",
      dsc: "Sabor suave de amêndoas",
      price: 10.0,
    },
    {
      id: "cake10",
      img: "../img/botões/Cakes.png",
      name: "Bolo de Limão Siciliano",
      dsc: "Fresco com raspas de limão siciliano",
      price: 10.0,
    },
    {
      id: "cake11",
      img: "../img/botões/Cakes.png",
      name: "Bolo de Nozes",
      dsc: "Delicado com nozes crocantes",
      price: 10.0,
    },
    {
      id: "cake12",
      img: "../img/botões/Cakes.png",
      name: "Bolo de Maracujá",
      dsc: "Azedinho doce de maracujá",
      price: 10.0,
    }
  ],
  cupcakes: [
    {
      id: "cupcake1",
      img: "../img/botões/Cupcakes.png",
      name: "Cupcake de Chocolate",
      dsc: "Mini delícia de chocolate",
      price: 10.0,
    },
    {
      id: "cupcake2",
      img: "../img/botões/Cupcakes.png",
      name: "Cupcake de Morango",
      dsc: "Sabor doce de morango",
      price: 10.0,
    },
    {
      id: "cupcake3",
      img: "../img/botões/Cupcakes.png",
      name: "Cupcake de Cenoura",
      dsc: "Com um toque de especiarias",
      price: 10.0,
    },
    {
      id: "cupcake4",
      img: "../img/botões/Cupcakes.png",
      name: "Cupcake de Hortelã",
      dsc: "Sabor refrescante de hortelã",
      price: 10.0,
    },
    {
      id: "cupcake5",
      img: "../img/botões/Cupcakes.png",
      name: "Cupcake de Limão",
      dsc: "Cítrico com cobertura suave",
      price: 10.0,
    },
    {
      id: "cupcake6",
      img: "../img/botões/Cupcakes.png",
      name: "Cupcake de Coco",
      dsc: "Sabor tropical de coco",
      price: 10.0,
    },
    {
      id: "cupcake7",
      img: "../img/botões/Cupcakes.png",
      name: "Cupcake de Baunilha",
      dsc: "Simples e delicioso",
      price: 10.0,
    },
    {
      id: "cupcake8",
      img: "../img/botões/Cupcakes.png",
      name: "Cupcake de Amêndoa",
      dsc: "Suave e crocante",
      price: 10.0,
    },
    {
      id: "cupcake9",
      img: "../img/botões/Cupcakes.png",
      name: "Cupcake de Framboesa",
      dsc: "Recheio de framboesa",
      price: 10.0,
    },
    {
      id: "cupcake10",
      img: "../img/botões/Cupcakes.png",
      name: "Cupcake de Caramelo",
      dsc: "Cobertura cremosa de caramelo",
      price: 10.0,
    },
    {
      id: "cupcake11",
      img: "../img/botões/Cupcakes.png",
      name: "Cupcake de Maçã e Canela",
      dsc: "Aromático com canela",
      price: 10.0,
    },
    {
      id: "cupcake12",
      img: "../img/botões/Cupcakes.png",
      name: "Cupcake de Maracujá",
      dsc: "Com toque tropical",
      price: 10.0,
    }
  ],
  donuts: [
    {
      id: "donut1",
      img: "../img/botões/Donuts.png",
      name: "Donut Glaceado",
      dsc: "Clássico glaceado",
      price: 10.0,
    },
    {
      id: "donut2",
      img: "../img/botões/Donuts.png",
      name: "Donut de Chocolate",
      dsc: "Com toque de chocolate",
      price: 10.0,
    },
    {
      id: "donut3",
      img: "../img/botões/Donuts.png",
      name: "Donut com Granulado",
      dsc: "Granulados coloridos",
      price: 10.0,
    },
    {
      id: "donut4",
      img: "../img/botões/Donuts.png",
      name: "Donut de Canela",
      dsc: "Doce e apimentado",
      price: 10.0,
    },
    {
      id: "donut5",
      img: "../img/botões/Donuts.png",
      name: "Donut de Doce de Leite",
      dsc: "Recheio cremoso",
      price: 10.0,
    },
    {
      id: "donut6",
      img: "../img/botões/Donuts.png",
      name: "Donut de Limão",
      dsc: "Sabor cítrico refrescante",
      price: 10.0,
    },
    {
      id: "donut7",
      img: "../img/botões/Donuts.png",
      name: "Donut de Caramelo",
      dsc: "Cobertura suave de caramelo",
      price: 10.0,
    },
    {
      id: "donut8",
      img: "../img/botões/Donuts.png",
      name: "Donut de Framboesa",
      dsc: "Recheio de framboesa",
      price: 10.0,
    },
    {
      id: "donut9",
      img: "../img/botões/Donuts.png",
      name: "Donut de Morango",
      dsc: "Coberto com glacê de morango",
      price: 10.0,
    },
    {
      id: "donut10",
      img: "../img/botões/Donuts.png",
      name: "Donut de Baunilha",
      dsc: "Cobertura cremosa de baunilha",
      price: 10.0,
    },
    {
      id: "donut11",
      img: "../img/botões/Donuts.png",
      name: "Donut de Coco",
      dsc: "Com toque de coco",
      price: 10.0,
    },
    {
      id: "donut12",
      img: "../img/botões/Donuts.png",
      name: "Donut de Chocolate Branco",
      dsc: "Cobertura de chocolate branco",
      price: 10.0,
    }
  ],
  cookies: [
    {
      id: "cookie1",
      img: "../img/botões/Cookies.png",
      name: "Cookie de Chocolate",
      dsc: "Um favorito atemporal",
      price: 10.0,
    },
    {
      id: "cookie2",
      img: "../img/botões/Cookies.png",
      name: "Cookie de Aveia",
      dsc: "Saudável e nutritivo",
      price: 10.0,
    },
    {
      id: "cookie3",
      img: "../img/botões/Cookies.png",
      name: "Cookie de Amendoim",
      dsc: "Rico sabor de amendoim",
      price: 10.0,
    },
    {
      id: "cookie4",
      img: "../img/botões/Cookies.png",
      name: "Cookie de Açúcar",
      dsc: "Clássico e doce",
      price: 10.0,
    },
    {
      id: "cookie5",
      img: "../img/botões/Cookies.png",
      name: "Cookie de Limão",
      dsc: "Crocante com toque cítrico",
      price: 10.0,
    },
    {
      id: "cookie6",
      img: "../img/botões/Cookies.png",
      name: "Cookie de Coco",
      dsc: "Com lascas de coco",
      price: 10.0,
    },
    {
      id: "cookie7",
      img: "../img/botões/Cookies.png",
      name: "Cookie de Gengibre",
      dsc: "Sabor picante e doce",
      price: 10.0,
    },
    {
      id: "cookie8",
      img: "../img/botões/Cookies.png",
      name: "Cookie de Canela",
      dsc: "Aroma suave de canela",
      price: 10.0,
    },
    {
      id: "cookie9",
      img: "../img/botões/Cookies.png",
      name: "Cookie de Amêndoa",
      dsc: "Com pedaços de amêndoa",
      price: 10.0,
    },
    {
      id: "cookie10",
      img: "../img/botões/Cookies.png",
      name: "Cookie de Caramelo",
      dsc: "Com recheio de caramelo",
      price: 10.0,
    },
    {
      id: "cookie11",
      img: "../img/botões/Cookies.png",
      name: "Cookie de Passas",
      dsc: "Passas suculentas",
      price: 10.0,
    },
    {
      id: "cookie12",
      img: "../img/botões/Cookies.png",
      name: "Cookie de Maracujá",
      dsc: "Azedinho e crocante",
      price: 10.0,
    }
  ],
  macarons: [
    {
      id: "macaron1",
      img: "../img/botões/macarons.png",
      name: "Macaron de Baunilha",
      dsc: "Doce creme de baunilha",
      price: 10.0,
    },
    {
      id: "macaron2",
      img: "../img/botões/macarons.png",
      name: "Macaron de Framboesa",
      dsc: "Recheio azedinho de framboesa",
      price: 10.0,
    },
    {
      id: "macaron3",
      img: "../img/botões/macarons.png",
      name: "Macaron de Pistache",
      dsc: "Sabor de pistache",
      price: 10.0,
    },
    {
      id: "macaron4",
      img: "../img/botões/macarons.png",
      name: "Macaron de Café",
      dsc: "Sabor intenso de café",
      price: 10.0,
    },
    {
      id: "macaron5",
      img: "../img/botões/macarons.png",
      name: "Macaron de Coco",
      dsc: "Com toque tropical de coco",
      price: 10.0,
    },
    {
      id: "macaron6",
      img: "../img/botões/macarons.png",
      name: "Macaron de Limão",
      dsc: "Sabor refrescante de limão",
      price: 10.0,
    },
    {
      id: "macaron7",
      img: "../img/botões/macarons.png",
      name: "Macaron de Amora",
      dsc: "Com recheio doce de amora",
      price: 10.0,
    },
    {
      id: "macaron8",
      img: "../img/botões/macarons.png",
      name: "Macaron de Frutas Vermelhas",
      dsc: "Recheio saboroso de frutas",
      price: 10.0,
    },
    {
      id: "macaron9",
      img: "../img/botões/macarons.png",
      name: "Macaron de Amêndoa",
      dsc: "Delicado com toque de amêndoa",
      price: 10.0,
    },
    {
      id: "macaron10",
      img: "../img/botões/macarons.png",
      name: "Macaron de Maracujá",
      dsc: "Azedinho de maracujá",
      price: 10.0,
    },
    {
      id: "macaron11",
      img: "../img/botões/macarons.png",
      name: "Macaron de Chocolate Branco",
      dsc: "Recheio de chocolate branco",
      price: 10.0,
    },
    {
      id: "macaron12",
      img: "../img/botões/macarons.png",
      name: "Macaron de Lavanda",
      dsc: "Aroma floral e delicado",
      price: 10.0,
    }
  ]
}